name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      #       - name: Set up .npmrc
      #         uses: actions/setup-node@v3
      #         with:
      #           node-version: '16.x'
      - name: Install dependecies
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi

      - name: Build
        run: npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v3.0.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
